version: '3.8'
services:
  microservice1.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - Microservices:Microservice2BaseUrl=http://microservice2.api:8080
    ports:
      - "5000:8080"
  microservice2.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5010:8080"
